Issue27
LorenzoBettini/example.exercise pull request #31
Opened 2016-11-24 15:50 UTC by Michedev

Close #27 
Implement SchoolController.addToDB(Student) method and Database.add(Student)

2016-11-25 09:43 UTC, LorenzoBettini requested changes

2016-11-25 09:43 UTC, LorenzoBettini commented on com.examples.exercise/src/test/java/com/examples/exercise/SchoolControllerTest.java
> +
Please remove this empty line

2016-11-25 09:43 UTC, LorenzoBettini commented on com.examples.exercise/src/test/java/com/examples/exercise/SchoolControllerTest.java
> +
Please remove this empty line

2016-11-25 09:43 UTC, LorenzoBettini commented on com.examples.exercise/src/test/java/com/examples/exercise/SchoolControllerTest.java
> +		verify(database, times(1)).exists(student.getId());
You might also want to check that database.add is NOT called

2016-11-25 14:49 UTC, LorenzoBettini commented
You also need to merge with master, since in the meantime another PR was merged and your PR cannot be merged: fetch from master, merge your branch with master and resolve conflicts, push your branch again (after you addressed all my other comments)

2016-11-27 23:02 UTC, Michedev commented
Sorry i read now about the conflicts and now i solved them

2016-11-28 16:45 UTC, Michedev commented
Test coverage is decreased because now DbMongo implemenets also the "add" method created by me for the issue

2016-11-28 16:49 UTC, LorenzoBettini approved these changes

2016-11-28 16:50 UTC, merged